version: '3.7'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:80'
    depends_on:
      - db
  db:
    image: 'microsoft/mssql-server-linux'
    environment:
      SA_PASSWORD: 'SuaSenhaDeAcesso'
      ACCEPT_EULA: 'Y'
    ports:
      - '1433:1433'
